### ISSUE TITLE
Error: It appears that you're using glslify in browserify without its transform applied.

### ISSUE THREAD

**Issue by stirlingpoon** [plotly/react-plotly.js#14] opened 2017-10-20 16:55 UTC
If the React project is created with create-react-app, this error is thrown:

```
Importing react-plotly.js throws "browser.js:2
Uncaught Error: It appears that you're using glslify in browserify without its transform applied. Make sure that you've set up glslify as a source transform" with React app created using create-react-app
```
It appears that this is caused by using Webpack, which create-react-app uses internally. Unfortunately, create-react-app doesn't expose the `webpack.config.js`/`webpack.config.json` files to apply the workaround in the README of https://github.com/plotly/plotly.js. I am using the workaround copied from https://github.com/jupyterlab/jupyter-renderers/issues/10:
```
import Plotly from 'plotly.js/lib/core';
import plotComponentFactory from 'react-plotly.js/factory';
const Plot = plotComponentFactory(Plotly);
```
But I would like to know if there's a better way. Thanks!

**Comment by rreusser** [comment] 2017-10-20 17:04
If you can't edit webpack config, then I think there are two and only two options:

1. Use the factory version of the component and a CDN-provided version of the component. This is the approach the [codepen example](https://codepen.io/rsreusser/pen/qPgwwJ) takes. If you can't edit the html, then you might have to use some sort of [async script loader](https://www.npmjs.com/package/script-loader) to load CDN plotly and proceed only when it's available.
2. Use the [eject](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-eject) command so that you can edit the config.

**Comment by rreusser** [comment] 2017-10-25 15:32
Closing as a duplicate of #13.

**Closed by rreusser** 2017-10-25 15:32 UTC
