### ISSUE TITLE
onRelayout Parameter

### ISSUE THREAD

**Issue by timothy-godfrey** [plotly/react-plotly.js#158] opened 2019-09-04 01:31 UTC
Possibly a bug, I get differently structured but deceptively similar parameters from the onRelayout event.

In the instance that onRelayout is triggered by a change to a rangeslider the event parameter is an object with 1 array called "xaxis.range":  
`eventParameter : { xaxis.range : [xmin, xmax] }`

In the instance that onRelayout is triggered by a scroll zoom action the event parameter is an object with 2 properties that are named in way that makes them appear like an array, but are not:  
`eventParameter : { xaxis.range[0] : xmin, xaxis.range[1] : xmax}`  

I'm not sure if this is by design or by accident, but it broke my code because I was doing a check like so:  
`if( typeof eventParameter["xaxis.range"] === 'undefined') { /code/ }`

In case it is relevant, part of the reason that I am only getting x axis values is because I have the y axes property 'fixedrange' set to true, and 'scrollZoom' set to true.

**Comment by etpinard** [comment] 2019-09-04 13:39
Duplicate of https://github.com/plotly/plotly.js/issues/1877

**Closed by etpinard** 2019-09-04 13:39 UTC
