### ISSUE TITLE
Axes labels disappearing for 3D scatter plot for non marker mode

### ISSUE THREAD

**Issue by lnunno** [plotly/react-plotly.js#33] opened 2018-01-18 23:27 UTC
I've made a simple repo that reproduces this issue: https://github.com/lnunno/react-plotly-axes-bug

If you change the mode to `'lines'` or `'markers+lines'` the axes labels disappear.

**Comment by nicolaskruchten** [comment] 2018-01-19 15:56
Thanks for this bug report! I can't actually replicate this behaviour outside of your repo, for example this works for me:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>react-plotly.js Scratch</title>
        <script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
        <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
        <script crossorigin src="https://cdn.plot.ly/plotly-1.33.0.min.js"></script>
        <script crossorigin src="https://unpkg.com/react-plotly.js@1.2.0/dist/create-plotly-component.js"></script>
    </head>
    <body>
        <div id="chart"> </div>
    <script>
        var gd = document.getElementById('chart')
        var data = [
            {
              x: [1, 2, 3],
              y: [4, 5, 6],
              z: [7, 8, 9],
              type: 'scatter3d',
              mode: 'lines+markers',
            }
          ];
        var layout = {};

        ReactDOM.render(
          React.createElement(createPlotlyComponent(Plotly),
            { data: data, layout: layout}), gd );

    </script>
    </body>
</html>
```

**Comment by lnunno** [comment] 2018-01-19 17:51
Any idea what might be causing this? My guess might be something with how the webpack integration might be working, although I've followed the instructions for that in the README. I'm seeing this fairly consistently with this webpack setup. 

I also experimented by using a ref directly and using the Plotly library and not React-Plotly but seeing the same behavior. I was also having some trouble getting the imports to work as specified as in [here](https://github.com/lnunno/react-plotly-axes-bug/blob/master/src/ts/webapp/index.tsx#L4). Was seeing runtime errors from react when using the default import e.g.

```ts
import Plot from 'react-plotly.js'; // Error
```

and 

```ts
import { Plot } from 'react-plotly.js'; // Error
```

Don't know if this is related, I see you using createReactPlotlyComponent, but I'm assuming that's integrated into how the module is exported.

**Comment by nicolaskruchten** [comment] 2018-01-23 19:25
OK, first things first: I was able to reproduce the axes issue with Webpack and without React or create-react-app or TypeScript, so the issue seems to be in the Webpack bundling step. I'll try to find a fix for this shortly, but I may need to involve some plotly.js people.

With respect to the imports `import Plot from 'react-plotly.js'` definitely works for multiple projects on this end, so let's create a new issue for that please, so as to stick to one problem/one Github issue :)

**Comment by nicolaskruchten** [comment] 2018-01-26 15:06
I believe we have a fix ready for this problem, it seems to be a dependency issue that shows up differently based on whether you install with `yarn` or `npm` :(

**Comment by lnunno** [comment] 2018-01-31 22:02
@nicolaskruchten Awesome, looking forward to the fix.

**Comment by nicolaskruchten** [comment] 2018-02-12 20:00
This should be fixed with the latest version of plotly.js. There were some issues with versions of `gl-shader` that were installing in a different order depending on whether you were using Yarn or NPM but the new version should be more deterministic/correct.

**Comment by nicolaskruchten** [comment] 2018-02-12 20:28
I've just tried your example app with the plotly.js version 1.34.0 and it works with both NPM and Yarn but please note that I had to erase `yarn.lock` and rebuild it in order to make it work, otherwise it still installed the wrong version of `gl-shader` for some dependencies for some reason that I'm struggling to understand.

**Comment by nicolaskruchten** [comment] 2018-02-12 20:29
(note that I'm assuming the error was from `gl-shader` based on some previous investigations but it might be something else too)

**Closed** 2018-03-07 20:46 UTC

**Comment by lnunno** [comment] 2018-03-07 23:46
Thanks, I've confirmed this works 👍
